name: destiny_decoder_app
description: Destiny Decoder mobile app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  flutter_riverpod: ^2.5.0
  riverpod: ^2.5.0
  go_router: ^14.0.0

